services:
  cloudflared:
    image: cloudflare/cloudflared:2026.8.3@sha256:51c9cefcb4569df44e1ad403ab1d3d8065aa8e84339bcfc6aee75502e1140339
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN={{ CF_TUNNEL_TOKEN }}
    networks:
      - proxy
    command: tunnel run
    volumes:
      - /home/scott/docker/cloudflared/config:/home/nonroot/.cloudflared/

networks:
  proxy:
    external: true
