services:
  cloudflared:
    image: cloudflare/cloudflared:2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN={{ CF_TUNNEL_TOKEN }}
    networks:
      - proxy
    command: tunnel run
    volumes:
      - /home/scott/docker/cloudflared/config:/home/nonroot/.cloudflared/

networks:
  proxy:
    external: true
