#!/usr/bin/env bash

MDSTAT='/proc/mdstat'

# check to make sure /proc/mdstat exists
if [ ! -f "$MDSTAT" ]; then
    echo "/proc/mdstat does not exist!"
    exit 3
fi

# see if there are multiple mdadm volumes...
devices=$(ls /dev | grep -e "^md[0-9]$")
declare -a devicestatus

for device in $devices; do
    status=$(mdadm --detail "/dev/$device" | grep -e '^\s*State : ' | awk '{ print $NF; }')

    if [[ $status != "clean" ]] && [[ $status != "active" ]]; then
        devicestatus+=("$status")
    fi
done

# At some point, maybe add a for loop here to print out the status of each one?
if [[ ! -z "${devicestatus[@]}" ]]; then
    printf "All mdadm volumes not clean! \n%s\n" "$devicestatus"
    exit 3
else
    echo "All mdadm volumes clean."
    exit 0
fi
