#!/bin/bash
# Nagios plugin to check the health of my immich database backups.


backup_dir=/syncthing/immich_backups
found=false

#check to make sure that $backup_dir exists and is a directory.
if [ ! -d "$backup_dir" ]; then
    echo "Error: Directory not found."
fi

for file in "$backup_dir"/*; do
    if [ -f "$file" ]; then
        file_age=$(($(date +%s) - $(stat -c %Y "$file")))

        if [ "$file_age" -lt 86400 ]; then
            found=true
            echo "Immich backup current." 
            exit 0
        fi
    fi
done

if [ "$found" = false ]; then
    echo "ERROR: Immich backup is not current!"
    exit 2
fi
