#!/usr/bin/bash

#Depends on Jim Salter's Sanoid tool to check snapshot health on a ZFS system.
# User must have a sudoer's policy that allows running this command with no password.

sudo /usr/sbin/sanoid --monitor-snapshots
