---
- name: reload systemd‑resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: yes 

- name: pihole-FTL
  ansible.builtin.service:
    name: pihole-FTL
    state: restarted
