---
services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:3.3.1@sha256:8657d0d1b79e7f008261bbb65c2f177a89e8a0fd325b9a312d16cf7b5cbee209
    container_name: immich-public-proxy
    restart: unless-stopped
    networks:
      - traefik
    environment:
      PUBLIC_BASE_URL: https://photos.{{ HOST_DOMAIN }}
      IMMICH_URL: https://{{ IMMICH_URL }}
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
    extra_hosts:
       - "{{ IMMICH_URL }}:10.13.37.11"
    labels:
      - traefik.enable=true
      - traefik.http.routers.immichproxy.entrypoints=websecure
      - traefik.http.routers.immichproxy.rule=Host(`photos.{{ HOST_DOMAIN }}`)
      - traefik.http.services.immichproxy.loadbalancer.server.port=3000
