---
services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:3.2.1@sha256:7ca34cc3efa618a11674db00e1d943e4611cb2e14d1f6d73343757db700a6e3c
    container_name: immich-public-proxy
    restart: unless-stopped
    networks:
      - traefik
    environment:
      PUBLIC_BASE_URL: https://photos.{{ HOST_DOMAIN }}
      IMMICH_URL: https://{{ IMMICH_URL }}
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
    extra_hosts:
       - "{{ IMMICH_URL }}:10.13.37.11"
    labels:
      - traefik.enable=true
      - traefik.http.routers.immichproxy.entrypoints=websecure
      - traefik.http.routers.immichproxy.rule=Host(`photos.{{ HOST_DOMAIN }}`)
      - traefik.http.services.immichproxy.loadbalancer.server.port=3000
