---

- hosts: all

  pre_tasks:

  - name: Update package cache.
    ansible.builtin.package:
      update_cache: true
      cache_valid_time: true
    become: true
    changed_when: false

- hosts: all
  become: true
  roles:
    #- bladewdr.alloy
    - bladewdr.basics
  tags: basics

- hosts: dns
  become: true
  roles:
    - bladewdr.pihole
    - bladewdr.bind9
  tags: dns

- hosts: unifi
  become: true
  roles:
    #- bladewdr.basics
    - bladewdr.qemu
    - bladewdr.unifi
  tags: unifi

- hosts: docker
  become: true
  roles:
    - geerlingguy.docker
  tags: docker
