---

- hosts: all

  pre_tasks:

  - name: Update package cache.
    ansible.builtin.package:
      update_cache: true
      cache_valid_time: true
    become: true
    changed_when: false

- hosts: all
  become: true
  roles:
    #- bladewdr.alloy
    - bladewdr.basics
    - bladewdr.chezmoi
  tags: basics

# - hosts: dns
#   become: true
#   roles:
#     - bladewdr.pihole
#     - bladewdr.bind9
#   tags: dns

# - hosts: gitlab
#   become: true
#   roles:
#     #- bladewdr.basics
#     - bladewdr.qemu
#     - bladewdr.gitlab
#   tags: gitlab

- hosts: docker
  become: true
  roles:
    - geerlingguy.docker
  tags: docker

- hosts: docker
  vars_files:
    - secrets.yml
  become: true
  roles:
    - ansible-role-docker-compose-generator
  tags: compose

  tasks:
    - name: Run docker compose up.
      ansible.builtin.shell: |
        cd {{ docker_compose_generator_output_path }}
        docker compose up -d --remove-orphans
      tags: compose
