#SPDX-License-Identifier: MIT-0
---

- name: Gitlab Reconfigure
  ansible.builtin.shell: |
    gitlab-ctl reconfigure
  environment:
    EXTERNAL_URL: "{{ gitlab_external_url }}"
    GITLAB_ROOT_EMAIL: "{{ gitlab_root_email }}"
    GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
