---
- name: Create Loki config file.
  ansible.builtin.template:
    src: loki-config.yml
    dest: /apps/grafana-stack/loki/config.yaml
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: '0644'

- name: Copy over the Docker Compose stack for Grafana, Prometheus, AlertManager, and Loki.
  ansible.builtin.template:
    src: grafana-stack-compose.j2
    dest: /apps/compose.yaml
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: '0755'
  notify: grafana compose up

- name: Create the backup script.
  ansible.builtin.template:
    src: grafana-backup.j2
    dest: /opt/grafana-backup.sh
    owner: root
    group: root
    mode: '0755'

- name: Create a cron job to run the backup script.
  ansible.builtin.cron:
    name: Back up Grafana data.
    job: /opt/grafana-backup.sh
    minute: "0"
    hour: "6"
    user: root
