---

pihole_default_password: "password"
pihole_force_install: false
pihole_ftl_branch: "master"
pihole_temp_dir: "/tmp/pihole-ansible"
pihole_web_git_url: "https://github.com/pi-hole/web.git"
pihole_git_url: "https://github.com/pi-hole/pi-hole.git"
pihole_web_root: "/var/www/html"
pihole_web_interface_dir: "{{ pihole_web_root }}/admin"
pihole_local_repo: "/etc/.pihole"
pihole_scripts:
  - piholeDebug
  - piholeFlush
  - setupLCD
  - update
  - version
  - gravity
  - uninstall
  - webpage
pihole_install_dir: "/opt/pihole"
pihole_config_dir: "/etc/pihole"
pihole_bin_dir: "/usr/local/bin"
pihole_v6_config_path: "{{ pihole_config_dir }}/pihole.toml"
pihole_ftl_location: "/usr/bin/pihole-FTL"
pihole_fresh_install: true
pihole_install_log: "{{ pihole_config_dir }}/install.log"
pihole_adlist_file: "{[ pihole_config_dir ]}/adlists.list"
pihole_dependencies_apt:
  - bash-completion
  - binutils
  - ca-certificates
  - cron
  - curl
  - dialog
  - dnsutils
  - dns-root-data
  - git
  - grep
  - iproute2
  - iputils-ping
  - man
  - jq
  - libcap2
  - libcap2-bin
  - lshw
  - netcat-openbsd
  - procps
  - psmisc
  - sudo
  - unzip

pihole_dependencies_rpm:
  - bash-completion
  - bind-utils
  - binutils
  - ca-certificates
  - chkconfig
  - cronie
  - curl
  - man
  - dialog
  - findutils
  - gawk
  - git
  - grep
  - iproute
  - jq
  - libcap
  - lshw
  - nmap-ncat
  - procps-ng
  - psmisc
  - sudo
  - unzip

pihole_upstream_dns_servers:
  - "1.1.1.1"
  - "8.8.8.8"

pihole_advanced_scripts:
  - api
  - list
  - piholeARPTable
  - query
  - piholeDebug
  - piholeLogFlush
  - update
  - updatecheck
  - piholeCheckout
  - version
  - utils

pihole_FTL_scripts:
  - pihole-FTL-prestart.sh
  - pihole-FTL-poststop.sh

pihole_manpage_dirs:
  - '/usr/local/share/man/man5'
  - '/usr/local/share/man/man8'

pihole_block_lists:
  - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts" # The default StevenBlack Unified Hosts list that comes with Pi-hole.

pihole_query_logging: "true"

# "0" "Show everything" on
# "1" "Hide domains" off
# "2" "Hide domains and clients" off
# "3" "Anonymous mode" off)
pihole_privacy_level: "0"

pihole_ftl_config:
  "dns.upstreams": "{{ pihole_upstream_dns_servers | to_json }}"
  "dns.queryLogging": "true"
  "dns.domainNeeded": "true"
  "dns.expandHosts": "true"
  "dns.listeningMode": "ALL"
  "dns.rateLimit.count": "0"
  "misc.privacylevel": "0"
  "misc.etc_dnsmasq_d": "true"
  "webserver.session.timeout": "300"
  "webserver.interface.theme": "default-darker"

# Who cares about 32-bit? This is 2025, people.
pihole_architecture_mapping:
  "aarch64": "arm64"
  "x86_64": "amd64"
