---

services:
  fivefilters-full-text-rss:
    container_name: fullrss
    restart: unless-stopped
    volumes:
      - "/home/scott/docker/fulltext/rss-cache:/var/www/html/cache"
      - "/home/scott/docker/fulltext/config:/custom/var/www/html/site_config/custom"
    image: 'heussd/fivefilters-full-text-rss:latest@sha256:a35e5e78e5d912fdc995dca61a8cf5fdff3938ca0f0c308644c184e4ea626f9f'
    environment:
      - FTR_ADMIN_PASSWORD={{ ffr_admin_password }}
    labels:
      - traefik.enable=true
      - traefik.http.routers.fullrss.rule=Host(`fulltext.lan.bladewdr.xyz`)
      - traefik.http.routers.fullrss.entrypoints=https
      - traefik.http.routers.fullrss.middlewares=default-headers@file,https-redirectscheme@file
      - traefik.http.routers.fullrss.tls=true
      - traefik.http.routers.fullrss.service=fullrss
      - traefik.http.services.fullrss.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true
