---

- name: "STARSHIP INSTALL - Download starship from Github to /tmp."
  ansible.builtin.get_url:
    url: "{{ starship_url }}"
    dest: "{{ starship_download_path }}"
    mode: '0755'

- name: "STARSHIP INSTALL - Extract the tarball."
  ansible.builtin.unarchive:
    src: "{{ starship_download_path }}"
    dest: "{{ starship_installation_directory }}"
    mode: '0755'
    remote_src: true

- name: "STARSHIP INSTALL - starship delete tarball"
  ansible.builtin.file:
    path: "{{ starship_download_path }}"
    state: absent
