---
services:
  food-tracker:
    image: git.bladewdr.xyz/scottb/food-tracker:v1.3.0@sha256:71149a6c11e7a6e7fc302a30a842fb51b3e3f86807ca7d085cedc6759c8f6d3a
    container_name: food-tracker
    restart: unless-stopped
    volumes:
      - /home/scott/docker/food-tracker/data:/app/data
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATA_DIR=/app/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.food-tracker.rule=Host(`food.{{ TRAEFIK_HOST_DOMAIN }}`)"
      - "traefik.http.routers.food-tracker.entrypoints=https"
      - "traefik.http.services.food-tracker.loadbalancer.server.port=3000"
      - "traefik.http.routers.food-tracker.tls=true"
      - "traefik.http.routers.food-tracker.service=food-tracker"
      - "traefik.http.routers.food-tracker.middlewares=default-headers@file"

networks:
  proxy:
    external: true
