---
volumes:
  kiwix-data:
    labels:
      - remove_volume_on=down
    driver_opts:
      type: nfs
      o: "addr=nas01.bladewdr.xyz,nolock,noatime,soft,rw"
      device: ":/mnt/tank/kiwix"

networks:
  proxy:
    external: true

services:
  kiwix-serve:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve:3.8.1@sha256:a105ef4c6791741224f0f6883fc391c4fe8bd25307be286e631d0a52e8777ef7
    networks:
      - proxy
    volumes:
      - kiwix-data:/data
    command:
      - '*.zim'
