---
volumes:
  kiwix-data:
    labels:
      - remove_volume_on=down
    driver_opts:
      type: nfs
      o: "addr=nas01.bladewdr.xyz,nolock,noatime,soft,rw"
      device: ":/mnt/tank/kiwix"

networks:
  proxy:
    external: true

services:
  kiwix-serve:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve:3.8.2@sha256:de4d451d9d9e3e2d37c1a7b5a861698c67cc4c52c364c2a593ba554cddd6ce03
    networks:
      - proxy
    volumes:
      - kiwix-data:/data
    command:
      - '*.zim'
    restart: unless-stopped
