---
volumes:
  kiwix-data:
    labels:
      - remove_volume_on=down
    driver_opts:
      type: nfs
      o: "addr=nas01.bladewdr.xyz,nolock,noatime,soft,rw"
      device: ":/mnt/tank/kiwix"

networks:
  proxy:
    external: true

services:
  kiwix-serve:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve:3.8.2@sha256:0b6541355b250c6b45d2d7725e88f22f1d6a0f45ad9480d9c0bd4bc58436a12f
    networks:
      - proxy
    volumes:
      - kiwix-data:/data
    command:
      - '*.zim'
