---

- name: Check SELinux status
  ansible.builtin.command: getenforce
  register: selinux_status
  changed_when: false

- name: Fail if SELinux is enforcing
  ansible.builtin.fail:
    msg: "SELinux is enforcing. Please disable or set to permissive before continuing."
  when: selinux_status.stdout == "Enforcing"

- name: Install Pi-hole dependencies (DNF).
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ pihole_dependencies_apt }}"
