---
services:
  dawarich:
    image: freikin/dawarich:1.14.1@sha256:65be16e1d261ea9a92c885eb8626e33ae46de6bfc6f6d6bce71c24eff2a6ae5f
    container_name: ${DAWARICH_CONTAINER_NAME:-dawarich}
    restart: ${DAWARICH_RESTART:-unless-stopped}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /apps/dawarich/storage:/var/app/storage
    networks:
      - traefik
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    environment:
      - BACKGROUND_PROCESSING_CONCURRENCY=3
      - RAILS_ENV=production
      - REDIS_URL=redis://dawarich_redis:6379
      - DATABASE_HOST=dawarich_db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=${DAWARICH_POSTGRES_USER:-postgres}
      - DATABASE_PASSWORD={{ DAWARICH_POSTGRES_PW }}
      - DATABASE_NAME=dawarich_production
      - DOMAIN={{ DAWARICH_HOST_NAME }}.{{ APP0_HOST_DOMAIN }}
      - MIN_MINUTES_SPENT_IN_CITY=${DAWARICH_MIN_MINS:-30}
      - APPLICATION_HOSTS=localhost,::1,127.0.0.1,{{ DAWARICH_HOST_NAME }}.{{ APP0_HOST_DOMAIN }}
      - TIME_ZONE={{ host_timezone }}
      - APPLICATION_PROTOCOL=http
      - PHOTON_API_HOST=dawarich_photon:2322
      - PHOTON_API_USE_HTTPS=false
      - PROMETHEUS_EXPORTER_ENABLED=false
      - PROMETHEUS_EXPORTER_HOST=0.0.0.0
      - PROMETHEUS_EXPORTER_PORT=9394
      - SELF_HOSTED=true
      - SECRET_KEY_BASE={{ DAWARICH_SECRET_KEY_BASE }}
      - RAILS_LOG_TO_STDOUT="true"
      # SMTP settings
      - SMTP_SERVER={{ SMTP_SERVER_ADDRESS }}
      - SMTP_PORT=587
      - SMTP_USERNAME={{ SMTP_USERNAME }}
      - SMTP_PASSWORD={{ SMTP_PASSWORD }}
      - SMTP_FROM=Dawarich <{{ SMTP_FROM }}>
      - SMTP_DOMAIN={{ SMTP_DOMAIN }}
      - SMTP_AUTHENTICATION=plain
      - SMTP_OPEN_TIMEOUT=25
      - SMTP_READ_TIMEOUT=25
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'"]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB
    labels:
      - joyride.host.name={{ DAWARICH_HOST_NAME }}.{{ APP0_HOST_DOMAIN }}
      - traefik.enable=${DAWARICH_TRAEFIK_ENABLED:-true}
      - traefik.http.routers.dawarich.entrypoints=websecure
      - traefik.http.routers.dawarich.rule=Host(`{{ DAWARICH_HOST_NAME }}.{{ APP0_HOST_DOMAIN }}`)
      # - traefik.http.services.dawarich.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.dawarich.loadbalancer.server.port=3000
      - autoheal=${DAWARICH_AUTOHEAL_ENABLED:-true}

  dawarich_sidekiq:
    image: freikin/dawarich:1.14.1@sha256:65be16e1d261ea9a92c885eb8626e33ae46de6bfc6f6d6bce71c24eff2a6ae5f
    container_name: dawarich_sidekiq
    volumes:
      - /apps/dawarich/public:/var/app/public
      - /apps/dawarich/watched:/var/app/tmp/imports/watched
      - /apps/dawarich/storage:/var/app/storage
    networks:
      - traefik
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['bundle', 'exec', 'sidekiq']
    restart: on-failure
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://dawarich_redis:6379
      - DATABASE_HOST=dawarich_db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=${DAWARICH_POSTGRES_USER:-postgres}
      - DATABASE_PASSWORD={{ DAWARICH_POSTGRES_PW }}
      - DATABASE_NAME=dawarich_production
      - DOMAIN=trips.bladewdr.xyz
      - APPLICATION_HOSTS=localhost,::1,127.0.0.1,{{ DAWARICH_HOST_NAME }}.{{ APP0_HOST_DOMAIN }}
      - BACKGROUND_PROCESSING_CONCURRENCY=3
      - APPLICATION_PROTOCOL=http
      - SELF_HOSTED=true
      - PHOTON_API_HOST=dawarich_photon:2322
      - PHOTON_API_USE_HTTPS=false
      - PROMETHEUS_EXPORTER_ENABLED=false
      - PROMETHEUS_EXPORTER_HOST=dawarich
      - PROMETHEUS_EXPORTER_PORT=9394
      - SECRET_KEY_BASE={{ DAWARICH_SECRET_KEY_BASE }}
      - RAILS_LOG_TO_STDOUT="true"
      - SMTP_SERVER={{ SMTP_SERVER_ADDRESS }}
      - SMTP_PORT=587
      - SMTP_USERNAME={{ SMTP_USERNAME }}
      - SMTP_PASSWORD={{ SMTP_PASSWORD }}
      - SMTP_FROM=Dawarich <{{ SMTP_FROM }}>
      - SMTP_DOMAIN={{ SMTP_DOMAIN }}
      - SMTP_AUTHENTICATION=plain
      - SMTP_OPEN_TIMEOUT=25
      - SMTP_READ_TIMEOUT=25
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f sidekiq" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '2G'

  dawarich_redis:
    image: redis:7.4-alpine@sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf
    container_name: dawarich_redis
    command: redis-server
    networks:
      - traefik
    volumes:
      - /apps/dawarich/redis:/var/shared/redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_db:
    image: postgis/postgis:17-3.5-alpine@sha256:fc07e7a034e013d50ada575673b798ca6277e000b8364e39e217f612d94bd9a5
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - /apps/dawarich/db:/var/lib/postgresql/data
    networks:
      - traefik
    environment:
      - POSTGRES_USER=${DAWARICH_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD={{ DAWARICH_POSTGRES_PW }}
      - POSTGRES_DB=dawarich_production
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_photon:
      container_name: dawarich_photon
      image: rtuszik/photon-docker:2.3@sha256:729f883612bde3215c156111b421d8e0a27b1eb411b92ef4a24bd587b8259b04
      networks:
        - traefik
      environment:
          - UPDATE_STRATEGY=SEQUENTIAL
          - UPDATE_INTERVAL=720h
          - REGION=usa
          # - APPRISE_URLS=pover://user@token  # Optional: notifications
      volumes:
          - /apps/photon:/photon/data
      restart: unless-stopped
