- hosts: all
  become: true
  serial: 1
  tasks:

    - name: Update all packages.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Check to see if /var/run/reboot-required exists.
      stat:
        path: /var/run/reboot-required
      register: reboot_needed

    - name: Reboot the machines that need it.
      reboot:
        reboot_timeout: 300
        test_command: whoami
      when: reboot_needed.stat.exists
