---
services:
  jellyfin-newsletter:
    container_name: jellyfin-newsletter
    image: 'ghcr.io/seaweedbraincy/jellyfin-newsletter:1.2.0@sha256:a8a0325cc11c7f2c9ce991a512d446475f906b26ead0a7d7bdabcdd111a43c04'
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ='{{ host_timezone }}'
    volumes:
      - '/apps/jellyfin-newsletter/config:/app/config'
