---
services:
  it-tools:
    container_name: it-tools
    restart: unless-stopped
    networks:
      - proxy
    image: ghcr.io/sharevb/it-tools:latest-en@sha256:ef524b1cd0fc8af6ae6419ca457abb84693b2627f60d530ebe35af9b30bd001c 

networks:
  proxy:
    external: true
