---
services:
  it-tools:
    container_name: it-tools
    restart: unless-stopped
    networks:
      - proxy
    image: ghcr.io/sharevb/it-tools:latest-en@sha256:dffbd73c6740b9ad48b2c8d630270a4bc5d3b7fccfd70f854a97577262fa7459 

networks:
  proxy:
    external: true
