---
services:
  it-tools:
    container_name: it-tools
    restart: unless-stopped
    networks:
      - proxy
    image: ghcr.io/sharevb/it-tools:latest-en@sha256:72b300e6a8203fa97346193d9e89d8344e15e6ee0797bfe299f31b640673d404 

networks:
  proxy:
    external: true
