---

services:
  ersatztv:
    image: jasongdove/ersatztv:v26.3.0@sha256:7c402e5f348184359e0951b44d55fb6db3df671fa77fc91dcbd609034d28778b
    container_name: ersatztv
    environment:
      - TZ=${ERSATZ_TZ:-America/New_York}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    ports:
      - 8409:8409
    volumes:
      - /apps/ersatztv/config:/root/.local/share/ersatztv
      - media:/media:ro
      - type: tmpfs
        target: /root/.local/share/etv-transcode
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  jellyfin-newsletter:
      container_name: jellyfin-newsletter
      image: 'ghcr.io/seaweedbraincy/jellyfin-newsletter:0.10.2@sha256:f6d76753da6b439ed149e85506c2638f7e16e3069ee78a0f52c703fd05a398f4'
      environment:
        USER_UID: 1000
        USER_GID: 1000
        TZ: 'America/New_York'
      volumes:
        - '/apps/jellyfin-newsletter/config:/app/config'

  jellyfin:
    image: linuxserver/jellyfin:10.11.6@sha256:5c7691c30033c7e880c253090735c4839cc032fcd51f3a794d5689d2c5637046
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - DOTNET_USE_POLLING_FILE_WATCHER=1 # Try to avoid hitting inotify-watchers limits with large libraries.
      - LIBVA_DRIVER_NAME=iHD
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "992"
    volumes:
      - /apps/jellyfin/config:/config
      - /apps/jellyfin/cache:/cache
      - media:/media
      - type: tmpfs
        target: /transcode
        tmpfs:
          size: "4294967296"
    restart: 'unless-stopped'
    healthcheck:
      test: curl --noproxy 'localhost' -Lk -fsS "http://localhost:8096" || exit 1
      interval: 30s
      timeout: 30s
      start_period: 10s
      retries: 3

  navidrome:
    image: deluan/navidrome:0.60.3@sha256:a5dce8f33304714dd138e870cca0dcab3d937ca236be1a9f2b97da009d1a0048
    user: 1000:1000
    ports:
      - 4533:4533
    restart: unless-stopped
    container_name: navidrome
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=999h
      - ND_MUSICFOLDER=/mnt/media/music
      - ND_BASEURL=https://music.lan.bladewdr.xyz
      - ND_DEFAULTTHEME=Catppuccin Macchiato
      - ND_ENABLEINSIGHTSCOLLECTOR=false
    volumes:
      - /apps/navidrome/config:/data
      - media:/mnt/media:ro

  plex:
    image: plexinc/pms-docker:1.43.0.10492-121068a07@sha256:1131c4cd21fa22f8196f749f1dbb69af306776c3c83c7f5b061e51dc49bcff7f
    container_name: plex
    restart: unless-stopped
    volumes:
      - media:/media
      - /apps/plex/config:/config
      - /apps/plex/config/transcode:/transcode
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=America/New_York
      - PLEX_UID=${PUID:-1000}
      - PLEX_GID=${PGID:-1000}
      - HOSTNAME=plex.lan.bladewdr.xyz
      - ADVERTISE_IP=https://plex.lan.bladewdr.xyz
      - VERSION=docker

  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest@sha256:cae0571c51a4590957873ccc668a226f146b19007c027e7e05b227d0cfb0ccaa
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8888:8888
    group_add:
          - "992"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - ./tmp:/tmp/unmanic
      - media:/mnt/media

  feishin:
    image: ghcr.io/jeffvli/feishin:1.8.0@sha256:1f6145f5925b4c586ca1450a213a2ad70de416e8d4cd787c0bc4f0d974479c28
    container_name: feishin
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SERVER_NAME=Navidrome
      - SERVER_LOCK=${FEISHIN_SERVER_LOCK:-true} # When true AND name/type/url are set, only username/password can be toggled
      - SERVER_TYPE=navidrome
      - SERVER_URL=https://{{ NAVIDROME_HOST }}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=002
      - TZ=America/New_York
    ports:
      - 9180:9180

volumes:
  media:
    driver_opts:
      type: nfs
      o: "addr=10.13.37.22,nolock,noatime,soft,rw"
      device: ":/mnt/tank/media"
