#!/bin/bash
# Nagios Plugin
# Monitor remaining disk space on all attached filesystems
# and report back if usage goes above 90% or if it's about to run out of inodes.
# Credit to Vivek Gite at cyberciti.biz for the bulk of this script.

DISK_ALERT=90

function check_space() {
    df -H | grep -vE '^Filesystem|tmpfs|cdrom' | awk '{ print $5 " " $1 }' | while read -r output;
do
    echo "$output"
    usep=$(echo "$output" | awk '{ print $1}' | cut -d'%' -f1 )
    partition=$(echo "$output" | awk '{ print $2 }' )
    if [ "$usep" -ge "$DISK_ALERT" ]; then
        echo "Running out of space \"$partition ($usep%)\" on $(hostname) as on $(date)" 
        #$RETURN_CODE=2
        exit 2 
    elif [ "$usep" -lt "$DISK_ALERT" ]; then
        echo "Disk space OK."
        exit 0
    fi
done
}

check_space
