---

# Setting the root user and password via env vars is not working.
# Need to redo my logic here.

- name: Load additional vars for Community edition.
  ansible.builtin.include_vars:
    file: Community.yml
  when: gitlab_edition == 'gitlab-ce'

- name: Load additional vars for Enterprise edition.
  ansible.builtin.include_vars:
    file: Enterprise.yml
  when: gitlab_edition == 'gitlab-ee'

- name: Check if the Gitlab repository has already been added. (APT)
  ansible.builtin.stat:
    path: "/etc/apt/sources.list.d/gitlab_{{ gitlab_edition }}.list"
  register: gitlab_repo_check_deb
  when: ansible_os_family == 'Debian'

- name: Check if the Gitlab repository has already been added. (RPM)
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/gitlab_{{ gitlab_edition }}.repo"
  register: gitlab_repo_check_rpm
  when: ansible_os_family == 'RedHat'

- name: "Add the {{ gitlab_edition_full }} deb repository."
  ansible.builtin.shell: |
    curl "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.deb.sh" | sudo bash
  when: ansible_os_family == 'Debian' and not gitlab_repo_check_deb.stat.exists

- name: "Add the {{ gitlab_edition_full }} rpm repository."
  ansible.builtin.shell: |
    curl "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.rpm.sh" | sudo bash
  when: ansible_os_family == 'RedHat' and not gitlab_repo_check_rpm.stat.exists

- name: "Install or upgrade {{ gitlab_edition_full }} (Debian / Ubuntu)."
  ansible.builtin.apt:
    name: "{{ gitlab_edition }}={{ gitlab_package_name }}"
    update_cache: true
  when: ansible_os_family == 'Debian'
  notify: Gitlab Reconfigure

- name: "Install or upgrade {{ gitlab_edition_full }} (Red Hat / Alma / Fedora)."
  ansible.builtin.yum:
    name: "{{ gitlab_edition }}={{ gitlab_package_name }}"
    update_cache: true
  when: ansible_os_family == 'RedHat'
  notify: Gitlab Reconfigure

- name: Configure GitLab SMTP settings.
  ansible.builtin.blockinfile:
    path: /etc/gitlab/gitlab.rb
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      # SMTP settings:
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "{{ gitlab_smtp_server }}"
      gitlab_rails['smtp_port'] = {{ gitlab_smtp_port }}
      gitlab_rails['smtp_user_name'] = "{{ gitlab_smtp_username }}"
      gitlab_rails['smtp_password'] = "{{ gitlab_smtp_password }}"
      gitlab_rails['smtp_domain'] = "{{ gitlab_smtp_domain }}"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
      gitlab_rails['gitlab_email_from'] = '{{ gitlab_email_from }}'
      gitlab_rails['gitlab_email_reply_to'] = '{{ gitlab_email_reply_to }}'
  notify: Gitlab Reconfigure
  when: gitlab_smtp_enabled | bool
