---

- hosts: docker
  tags: compose
  gather_facts: false
  
  tasks:

    - name: Run docker compose down.
      ansible.builtin.shell: |
        cd {{ docker_compose_generator_output_path }}
        docker compose down
