---

services:
  joplin-db:
    image: postgres:16@sha256:be01cf82fc7dbba824acf0a82e150b4b360f3ff93c6631d7844af431e841a95c
    container_name: joplin_postgres
    restart: unless-stopped
    networks:
      - proxy
    environment:
      POSTGRES_DB: joplin
      POSTGRES_USER: joplin
      POSTGRES_PASSWORD: {{ joplin_postgres_pw }}
    volumes:
      - /home/scott/docker/joplin/db:/var/lib/postgresql/data

  joplin-app:
    image: joplin/server:3.7.1@sha256:0877bfba41a943017c42c58e90db9d8d548bfe699b5e410248b5b879371734f9
    container_name: joplin_server
    restart: unless-stopped
    depends_on:
      - joplin-db
    ports:
      - "22300:22300"
    networks:
      - proxy
    environment:
      - APP_PORT=22300
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD={{ joplin_postgres_pw }}
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=joplin-db
      - APP_BASE_URL=https://joplin.{{ TRAEFIK_HOST_DOMAIN }}
      - MAILER_ENABLED=1
      - MAILER_HOST={{ SMTP_SERVER_ADDRESS }}
      - MAILER_PORT=465
      - MAILER_SECURITY=tls
      - MAILER_AUTH_USER={{ SMTP_USERNAME }}
      - MAILER_AUTH_PASSWORD={{ SMTP_PASSWORD }}
      - MAILER_NOREPLY_NAME=Joplin Server
      - MAILER_NOREPLY_EMAIL={{ SMTP_FROM }}
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.joplin.rule=Host(`joplin.{{ TRAEFIK_HOST_DOMAIN }}`)
      - traefik.http.routers.joplin.entrypoints=https
      - traefik.http.routers.joplin.middlewares=default-headers@file
      - traefik.http.routers.joplin.tls=true
      - traefik.http.services.joplin.loadbalancer.server.port=22300

networks:
  proxy:
    external: true
