services:
  bentopdf:
    image: bentopdfteam/bentopdf:2.6.0@sha256:96709a7ecd64a3fb4adf4dcf320808248a565993ea0c67febd25da12a34dcab7
    container_name: bentopdf
    restart: unless-stopped
    networks:
        - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.bentopdf.rule=Host(`pdf.{{ TRAEFIK_HOST_DOMAIN }}`)
      - traefik.http.routers.bentopdf.entrypoints=https
      - traefik.http.routers.bentopdf.middlewares=default-headers@file,https-redirectscheme@file,dynamic
      - traefik.http.routers.bentopdf.tls=true
      - traefik.http.routers.bentopdf.service=bentopdf
      - traefik.http.services.bentopdf.loadbalancer.server.port=8080
      - sablier.enable=true
      - sablier.group=sablier
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
