services:
  server:
    image: docker.gitea.com/gitea:1.24.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD={{ GITEA_DB_PASSWORD }}
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__FROM={{ SMTP_FROM }}
      - GITEA__mailer__PROTOCOL=smtps
      - GITEA__mailer__SMTP_ADDR={{ SMTP_SERVER_ADDRESS }}
      - GITEA__mailer__SMTP_PORT={{ SMTP_PORT }}
      - GITEA__mailer__USER={{ SMTP_FROM }}
      - GITEA__mailer__PASSWD={{ SMTP_PASSWORD }}
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    container_name: gitea_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD={{ GITEA_DB_PASSWORD }}
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./gitea-psql:/var/lib/postgresql/data

networks:
  gitea:
    external: false
