---

- name: Install EPEL respositories.
  ansible.builtin.dnf:
      name: epel-release
      state: present
      update_cache: true
  when: ansible_os_family == 'RedHat'
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python

- name: Enable CodeReady Builder on RHEL
  community.general.rhsm_repository:
    name: "codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms"
    state: enabled
  when: ansible_distribution == "RedHat"

- name: Enable CRB on Rocky 8.
  ansible.builtin.command: dnf config-manager --set-enabled powertools
  changed_when: false
  when:
    - ansible_distribution == "Rocky"
    - ansible_distribution_major_version == "8"

- name: Enable CRB on Rocky 9+.
  ansible.builtin.command: dnf config-manager --set-enabled crb
  changed_when: false
  when:
    - ansible_distribution == "Rocky"
    - ansible_distribution_major_version > "8"

- name: Install basic packages.
  ansible.builtin.dnf:
    name: "{{ basic_packages_rpm }}"
    state: present
  when: ansible_os_family == 'RedHat'
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python

- name: Install QEMU Guest Agent on KVM virtual machines.
  ansible.builtin.dnf:
    name: qemu-guest-agent
    state: present
  notify: enable and start guest agent
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  when:
    - ansible_virtualization_role == 'guest'
    - ansible_virtualization_type == 'kvm'
    - "'cloud' not in group_names"

- name: Configure DNF automatic.
  block:
    - name: Install DNF automatic.
      ansible.builtin.dnf:
        name: dnf-automatic
        state: present
      vars:
        ansible_python_interpreter: /usr/libexec/platform-python

    - name: Set up automatic security updates.
      ansible.builtin.copy:
        src: dnf-automatic.conf
        dest: /etc/dnf/automatic.conf
        owner: root
        group: root
        mode: '0744'

    - name: Enable the DNF automatic systemd timer.
      ansible.builtin.systemd_service:
        name: dnf-automatic.timer
        state: started
        enabled: true

- name: Check if Homebrew directory already exists.
  ansible.builtin.stat:
    path: "/home/linuxbrew/.linuxbrew"
  register: brew_installed

- name: Install Homebrew.
  ansible.builtin.include_tasks: Homebrew.yml
  when: not brew_installed.stat.exists and (ansible_os_family == "Debian" or ansible_os_family == "RedHat")

- name: Get the user ID of the Ansible service account.
  ansible.builtin.command: whoami
  register: homebrew_user
  become: false
  changed_when: false

- name: Get the current owner of the Homebrew directory.
  ansible.builtin.stat:
    path: "/home/linuxbrew/.linuxbrew/"
  register: homebrew_stat

- name: Set Homebrew directory permissions.
  ansible.builtin.file:
    dest: "/home/linuxbrew/.linuxbrew/"
    owner: "{{ homebrew_user.stdout }}"
    group: "{{ homebrew_user.stdout }}"
    mode: '0775'
    recurse: true
  when: 
    - homebrew_stat.stat.pw_name != homebrew_user.stdout
    - not ansible_check_mode

- name: Install specific packages via Homebrew.
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
  become: false
  loop: "{{ brew_packages }}"
  when: ansible_os_family == "Debian"
